version: '3'
services:
    api:
        build: .
        ports:
            - 5000:5000
        depends_on:
            - postgres-db
        volumes:
            - './:/usr/src/app'
            - 'reserved:/usr/src/app/node_modules'
    postgres-db:
        image: postgres:latest
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: kampong-local
volumes:
    reserved:
