INSERT INTO location (location_name, zone) VALUES
('Admiralty', 'North'),
('Kranji', 'North'),
('Woodlands', 'North'),
('Sembawang', 'North'),
('Yishun', 'North'),
('Yio Chu Kang', 'North'),
('Seletar', 'North'),
('Sengkang', 'North'),
('Holland', 'South'),
('Queenstown', 'South'),
('Bukit Merah', 'South'),
('Telok Blangah ', 'South'),
('Pasir Panjang', 'South'),
('Sentosa', 'South'),
('Bukit Timah', 'South'),
('Newtown', 'South'),
('Orchard', 'South'),
('City', 'South'),
('Marina South', 'South'),
('Serangoon', 'East'),
('Punggol', 'East'),
('Hougang', 'East'),
('Tampines', 'East'),
('Pasir Ris', 'East'),
('Loyang', 'East'),
('Simei', 'East'),
('Kallang', 'East'),
('Katong', 'East'),
('East Coast', 'East'),
('Macpherson', 'East'),
('Bedok', 'East'),
('Pulau Ubin', 'East'),
('Lim Chu Kang', 'West'),
('Chao Chu Kang', 'West'),
('Bukit Panjang', 'West'),
('Jurong East', 'West'),
('Jurong West', 'West'),
('Bukit Batok', 'West'),
('Hillview', 'West'),
('West Coast', 'West'),
('Clementi', 'West'),
('Thomson', 'Central'),
('Sin Ming', 'Central'),
('Bishan', 'Central'),
('Ang Mo Kio', 'Central'),
('Toa Payoh', 'Central');

INSERT INTO category (category_name, category_group) VALUES
('Health', 'Social'),
('Marriage', 'Social'),
('Education', 'Social'),
('Mentorship', 'Social'),
('Retirement', 'Social'),
('Housing', 'Social'),
('Rental Flats', 'Social'),
('Family', 'Social'),
('Gender', 'Social'),
('Elderly', 'Social'),
('Youth', 'Social'),
('Youth At Risk', 'Social'),
('Pre-School', 'Social'),
('Race', 'Social'),
('Language', 'Social'),
('Science', 'Social'),
('Art', 'Social'),
('Sports', 'Social'),
('Poverty', 'Social'),
('Inequality', 'Social'),
('Recycling', 'Environment'), 
('Green', 'Environment'), 
('Water', 'Environment'), 
('Waste', 'Environment'), 
('Food', 'Environment'), 
('Growing', 'Environment'),
('Finance', 'Economy'),
('Jobs', 'Economy'),
('Wage', 'Economy'),
('Upskill', 'Economy'),
('Technology', 'Economy'),
('IT', 'Economy'),
('IoT 4.0', 'Economy'),
('Information', 'Economy'),
('Automation', 'Economy'),
('Online', 'Economy'),
('Digitalization', 'Economy'),
('Productivity', 'Others'), 
('Innovation', 'Others'), 
('Research', 'Others'), 
('Manpower', 'Others'), 
('Design', 'Others');
