INSERT INTO Locations (location) VALUES
('Admiralty'),
('Kranji'),
('Woodlands'),
('Sembawang'),
('Yishun'),
('Yio Chu Kang'),
('Seletar'),
('Sengkang'),
('Holland'),
('Queenstown'),
('Bukit Merah'),
('Telok Blangah '),
('Pasir Panjang'),
('Sentosa'),
('Bukit Timah'),
('Newtown'),
('Orchard'),
('City'),
('Marina South'),
('Serangoon'),
('Punggol'),
('Hougang'),
('Tampines'),
('Pasir Ris'),
('Loyang'),
('Simei'),
('Kallang'),
('Katong'),
('East Coast'),
('Macpherson'),
('Bedok'),
('Lim Chu Kang'),
('Chao Chu Kang'),
('Bukit Panjang'),
('Jurong East'),
('Jurong West'),
('Bukit Batok'),
('Hillview'),
('West Coast'),
('Clementi'),
('Thomson'),
('Sin Ming'),
('Bishan'),
('Ang Mo Kio'),
('Toa Payoh');
