/* Skills mock data population */
INSERT INTO "public"."skills" ("skill", "skill_group") VALUES
('Needs Analysis', 'Big Data Analysis'),
('Quantitative Research', 'Big Data Analysis'),
('Statistical Analysis', 'Big Data Analysis'),
('Compiling Statistics', 'Big Data Analysis'),
('Database Management', 'Big Data Analysis'),
('Modeling', 'Big Data Analysis'),
('Data Analytics', 'Big Data Analysis'),
('Phone Applications', 'Coding and Programming'),
('Design UIUX', 'Coding and Programming'),
('Website Building', 'Coding and Programming'),
('Benchmarking', 'Project Management'),
('Budget Planning', 'Project Management'),
('Operations', 'Project Management'),
('Quality Assurance', 'Project Management'),
('Scheduling', 'Project Management'),
('Fund Raiser', 'Project Management'),
('Administrative', 'Project Management'),
('Microsoft Office Skills', 'Project Management'),
('Negotiations', 'Project Management'),
('Public Speaking', 'Project Management'),
('Content Management System', 'Social Media Experience'),
('Digital Marketing', 'Social Media Experience'),
('Networking', 'Social Media Experience'),
('Search Engine Optimisation', 'Social Media Experience'),
('Social Media Platforms', 'Social Media Experience'),
('Web Analytics', 'Social Media Experience'),
('Sales', 'Social Media Experience'),
('Automated Marketing Software', 'Social Media Experience'),
('Graphic Design', 'Social Media Experience'),
('Research', 'Writing'),
('Emails', 'Writing'),
('Client Relations', 'Writing'),
('Technical Documentation', 'Writing'),
('Requirements Gathering', 'Writing');

INSERT INTO Locations (location) VALUES
('Admiralty'),
('Kranji'),
('Woodlands'),
('Sembawang'),
('Yishun'),
('Yio Chu Kang'),
('Seletar'),
('Sengkang'),
('Holland'),
('Queenstown'),
('Bukit Merah'),
('Telok Blangah '),
('Pasir Panjang'),
('Sentosa'),
('Bukit Timah'),
('Newtown'),
('Orchard'),
('City'),
('Marina South'),
('Serangoon'),
('Punggol'),
('Hougang'),
('Tampines'),
('Pasir Ris'),
('Loyang'),
('Simei'),
('Kallang'),
('Katong'),
('East Coast'),
('Macpherson'),
('Bedok'),
('Lim Chu Kang'),
('Chao Chu Kang'),
('Bukit Panjang'),
('Jurong East'),
('Jurong West'),
('Bukit Batok'),
('Hillview'),
('West Coast'),
('Clementi'),
('Thomson'),
('Sin Ming'),
('Bishan'),
('Ang Mo Kio'),
('Toa Payoh');
