import * as Knex from 'knex';

export async function seed(knex: Knex): Promise<void> {
    return knex.transaction(async (tx: Knex.Transaction) => {
        // Inserts seed entries
        await tx('location').insert([
            { location_name: 'Admiralty', zone: 'North' },
            { location_name: 'Kranji', zone: 'North' },
            { location_name: 'Woodlands', zone: 'North' },
            { location_name: 'Sembawang', zone: 'North' },
            { location_name: 'Yishun', zone: 'North' },
            { location_name: 'Yio Chu Kang', zone: 'North' },
            { location_name: 'Seletar', zone: 'North' },
            { location_name: 'Sengkang', zone: 'North' },
            { location_name: 'Holland', zone: 'South' },
            { location_name: 'Queenstown', zone: 'South' },
            { location_name: 'Bukit Merah', zone: 'South' },
            { location_name: 'Telok Blangah ', zone: 'South' },
            { location_name: 'Pasir Panjang', zone: 'South' },
            { location_name: 'Sentosa', zone: 'South' },
            { location_name: 'Bukit Timah', zone: 'South' },
            { location_name: 'Newtown', zone: 'South' },
            { location_name: 'Orchard', zone: 'South' },
            { location_name: 'City', zone: 'South' },
            { location_name: 'Marina South', zone: 'South' },
            { location_name: 'Serangoon', zone: 'East' },
            { location_name: 'Punggol', zone: 'East' },
            { location_name: 'Hougang', zone: 'East' },
            { location_name: 'Tampines', zone: 'East' },
            { location_name: 'Pasir Ris', zone: 'East' },
            { location_name: 'Loyang', zone: 'East' },
            { location_name: 'Simei', zone: 'East' },
            { location_name: 'Kallang', zone: 'East' },
            { location_name: 'Katong', zone: 'East' },
            { location_name: 'East Coast', zone: 'East' },
            { location_name: 'Macpherson', zone: 'East' },
            { location_name: 'Bedok', zone: 'East' },
            { location_name: 'Pulau Ubin', zone: 'East' },
            { location_name: 'Lim Chu Kang', zone: 'West' },
            { location_name: 'Chao Chu Kang', zone: 'West' },
            { location_name: 'Bukit Panjang', zone: 'West' },
            { location_name: 'Jurong East', zone: 'West' },
            { location_name: 'Jurong West', zone: 'West' },
            { location_name: 'Bukit Batok', zone: 'West' },
            { location_name: 'Hillview', zone: 'West' },
            { location_name: 'West Coast', zone: 'West' },
            { location_name: 'Clementi', zone: 'West' },
            { location_name: 'Thomson', zone: 'Central' },
            { location_name: 'Sin Ming', zone: 'Central' },
            { location_name: 'Bishan', zone: 'Central' },
            { location_name: 'Ang Mo Kio', zone: 'Central' },
            { location_name: 'Toa Payoh', zone: 'Central' },
        ]);

        await tx('category').insert([
            { category_name: 'Health', category_group: 'Social' },
            { category_name: 'Marriage', category_group: 'Social' },
            { category_name: 'Education', category_group: 'Social' },
            { category_name: 'Mentorship', category_group: 'Social' },
            { category_name: 'Retirement', category_group: 'Social' },
            { category_name: 'Housing', category_group: 'Social' },
            { category_name: 'Rental Flats', category_group: 'Social' },
            { category_name: 'Family', category_group: 'Social' },
            { category_name: 'Gender', category_group: 'Social' },
            { category_name: 'Elderly', category_group: 'Social' },
            { category_name: 'Youth', category_group: 'Social' },
            { category_name: 'Youth At Risk', category_group: 'Social' },
            { category_name: 'Pre-School', category_group: 'Social' },
            { category_name: 'Race', category_group: 'Social' },
            { category_name: 'Language', category_group: 'Social' },
            { category_name: 'Science', category_group: 'Social' },
            { category_name: 'Art', category_group: 'Social' },
            { category_name: 'Sports', category_group: 'Social' },
            { category_name: 'Poverty', category_group: 'Social' },
            { category_name: 'Inequality', category_group: 'Social' },
            { category_name: 'Recycling', category_group: 'Environment' },
            { category_name: 'Green', category_group: 'Environment' },
            { category_name: 'Water', category_group: 'Environment' },
            { category_name: 'Waste', category_group: 'Environment' },
            { category_name: 'Food', category_group: 'Environment' },
            { category_name: 'Growing', category_group: 'Environment' },
            { category_name: 'Finance', category_group: 'Economy' },
            { category_name: 'Jobs', category_group: 'Economy' },
            { category_name: 'Wage', category_group: 'Economy' },
            { category_name: 'Upskill', category_group: 'Economy' },
            { category_name: 'Technology', category_group: 'Economy' },
            { category_name: 'IT', category_group: 'Economy' },
            { category_name: 'IoT 4.0', category_group: 'Economy' },
            { category_name: 'Information', category_group: 'Economy' },
            { category_name: 'Automation', category_group: 'Economy' },
            { category_name: 'Online', category_group: 'Economy' },
            { category_name: 'Digitalization', category_group: 'Economy' },
            { category_name: 'Productivity', category_group: 'Others' },
            { category_name: 'Innovation', category_group: 'Others' },
            { category_name: 'Research', category_group: 'Others' },
            { category_name: 'Manpower', category_group: 'Others' },
            { category_name: 'Design', category_group: 'Others' },
        ]);
    });
}
