name: Build

on: [push]

jobs:
    build:
        runs-on: ubuntu-20.04

        strategy:
            matrix:
                node-version: '14'

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ node-version }}
                  check-latest: true
            - run: npm install -g yarn
            - name: Install dependencies, check formatting, and build
              run: |
                  yarn install
                  yarn prettier --check .
                  yarn build
