name: Deploy server

on:
    workflow_dispatch:
        inputs:
            server_type:
                description: 'Deploy to dev / staging / prod'
                required: true
                default: 'dev'

jobs:
    deploy:
        runs-on: ubuntu-20.04
        steps:
            - uses: webfactory/ssh-agent@v0.4.1
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            - name: Run deployment script on development
              if: github.event.inputs.server_type == 'dev'
              uses: appleboy/ssh-action@master
              with:
                  HOST: ${{ secrets.DEV_HOST }}
                  USERNAME: root
                  PORT: 22
                  KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: ~/deployment-scripts/update-backend.sh dev
            - name: Run deployment script on staging
              if: github.event.inputs.server_type == 'staging'
              uses: appleboy/ssh-action@master
              with:
                  HOST: ${{ secrets.DEV_HOST }}
                  USERNAME: root
                  PORT: 22
                  KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: ~/deployment-scripts/update-backend.sh staging
            - name: Run deployment script on production
              if: github.event.inputs.server_type == 'prod'
              uses: appleboy/ssh-action@master
              with:
                  HOST: ${{ secrets.PROD_HOST }}
                  USERNAME: root
                  PORT: 22
                  KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: ~/deployment-scripts/update-backend.sh prod
