name: API Docs

on:
    pull_request:
        types: [ready_for_review, review_requested]

jobs:
    build:
        runs-on: macos-latest

        steps:
            - name: Check out repository
              uses: actions/checkout@v2
            - name: Use Node.js 14
              uses: actions/setup-node@v2-beta
              with:
                  node-version: '14'
                  check-latest: true
            - name: Download Postman collection directly into repository and run json formatter script for docgen
              run: |
                  curl -H "x-api-key: ${{secrets.POSTMAN_API_KEY}}" https://api.getpostman.com/collections/b09bd8c5-776a-4d8c-8b71-f528c017cb08 -o ./public/api-docs/kampong-api.json
                  node .github/utils/formatApiDocs.js
            - name: Download docgen and generate API Docs
              run: |
                  curl https://raw.githubusercontent.com/thedevsaddam/docgen/v3/install.sh -o ~/install.sh && sudo chmod +x ~/install.sh && sudo ~/install.sh
                  docgen build -i ./public/api-docs/kampong-api.json -o ./public/api-docs/index.html
                  docgen build -i ./public/api-docs/kampong-api.json -o ./public/api-docs/index.md -m
            - name: Commit changes and push to current branch
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: Apply api docs updates
